### PR TITLE
Bleeding edge base

### PR DESCRIPTION
**Pull request by jroweboy**

### CODE REVIEW

**Comment by JayFoxRox** [comment]
Can we please rename this to something more obvious? like `bleeding-edge-base` as a branch name and a similar title? (The mergelog might show PR titles in the future)

This should also get a cleanup / split different parts into different commits.
It's important we keep these bleeding-edge builds maintainable, and a +12k line PR without doc and a misleading name is not maintainable ;)

---

More importantly, can we please move the updater/tag stuff to src/common (don't forget to move configure_file)? That way we can re-use it for the frontend window title to fix #6

**Comment by emmauss** [comment]
this is preventing new BE builds from building.

**Comment by JayFoxRox** [comment]
Yes, this needs to be fixed ASAP. Not sure what lemonbot will push, but it could be a *very* broken release..

@jroweboy

**Comment by jroweboy** [comment]
the code to upload a release is a part of this branch, so the only thing
that happens when it is pushed is a build is made but its not published.

**Comment by jroweboy** [comment]
Closed in favor of the rebased + actually has a description with a good branch name PR

**Pull request closed without merging**
